package review

import (
	"path/filepath"
	"strings"

	"github.com/codepilot-ai/codepilot-ai/internal/llm"
	"github.com/codepilot-ai/codepilot-ai/internal/models"
)

// autoGeneratedSuffixes lists file patterns that are auto-generated and not worth reviewing.
var autoGeneratedSuffixes = []string{
	"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "go.sum",
	"Gemfile.lock", "composer.lock", "Cargo.lock", "poetry.lock",
	".min.js", ".min.css", ".map", ".snap",
}

// isAutoGenerated returns true for lock files and auto-generated files not worth reviewing.
func isAutoGenerated(filename string) bool {
	base := filepath.Base(filename)
	for _, suffix := range autoGeneratedSuffixes {
		if strings.HasSuffix(base, suffix) || base == suffix {
			return true
		}
	}
	return false
}

// hasCriticalFindings checks if any finding has critical severity.
func hasCriticalFindings(findings []llm.ReviewFinding) bool {
	for _, f := range findings {
		if f.Severity == models.SeverityCritical {
			return true
		}
	}
	return false
}
